const generalNodes = [
  {
    id: "computer-occupation",
    name: "Computer (occupation)",
    description:
      "Established computing as a profession, laying groundwork for future developments.",
    year: "1613-1950s",
    url: "https://en.wikipedia.org/wiki/Computer_(occupation)",
    tags: ["1800s–1930s"],
    dependsOn: [],
  },
  {
    id: "difference-engine",
    name: "Difference Engine",
    description:
      "Mechanical calculator designed to tabulate polynomial functions, considered a precursor to modern computers.",
    year: 1822,
    url: "https://en.wikipedia.org/wiki/Difference_engine",
    tags: ["1800s–1930s", "hardware"],
    dependsOn: ["computer-occupation"],
  },
  {
    id: "analytical-engine",
    name: "Analytical Engine",
    description:
      "First conceptual design for a general-purpose computing machine.",
    year: 1837,
    url: "https://en.wikipedia.org/wiki/Analytical_Engine",
    tags: ["1800s–1930s", "hardware-concept", "early-computing"],
    dependsOn: ["difference-engine"],
  },
  {
    id: "boolean-algebra",
    name: "Boolean algebra",
    description:
      "Mathematical basis for digital circuit design, fundamental to computer science.",
    year: 1854,
    url: "https://en.wikipedia.org/wiki/Boolean_algebra",
    tags: ["1800s–1930s", "theoretical-foundation"],
    dependsOn: [],
  },
  {
    id: "predicate-logic",
    name: "Predicate logic",
    description:
      "Formal system for quantified statements and predicates, providing a foundation for computational logic and programming language theory.",
    year: 1879,
    url: "https://en.wikipedia.org/wiki/First-order_logic",
    tags: ["1800s–1930s", "theoretical-foundation"],
    influencedBy: ["boolean-algebra"],
  },
  {
    id: "differential-analyzer",
    name: "Differential Analyzer",
    description:
      "Early mechanical analog computer designed to solve differential equations.",
    year: 1931,
    url: "https://en.wikipedia.org/wiki/Differential_analyser",
    tags: ["1800s–1930s", "hardware", "early-computing"],
    dependsOn: ["difference-engine", "analytical-engine"],
  },
  {
    id: "turing-machine",
    name: "Turing Machine",
    description:
      "Provided theoretical basis for computation, fundamental to computer science.",
    year: 1936,
    url: "https://en.wikipedia.org/wiki/Turing_machine",
    tags: ["1800s–1930s", "theoretical-foundation"],
    dependsOn: ["predicate-logic", "boolean-algebra"],
  },
  {
    id: "z1-computer",
    name: "Z1 Computer",
    description:
      "First programmable (using punched tape), electrically driven mechanical calculator, employing binary arithmetic and floating-point numbers.",
    year: 1936,
    url: "https://en.wikipedia.org/wiki/Z1_(computer)",
    tags: ["1800s–1930s", "hardware", "early-computing"],
    dependsOn: ["boolean-algebra"],
  },
  {
    id: "z3",
    name: "Z3 Computer",
    description:
      "First fully automatic, programmable (using punched tape) electromechanical computer.",
    year: 1941,
    url: "https://en.wikipedia.org/wiki/Z3_(computer)",
    tags: ["1940s", "hardware", "early-computing"],
    dependsOn: ["z1-computer"],
  },
  {
    id: "abc-atanasoff-berry-computer",
    name: "Atanasoff-Berry Computer",
    description:
      "First electronic digital computer, not programmable. Designed for solving linear equations.",
    year: 1942,
    url: "https://en.wikipedia.org/wiki/Atanasoff%E2%80%93Berry_computer",
    tags: ["1940s", "hardware", "early-computing"],
    dependsOn: ["differential-analyzer"],
  },
  {
    id: "colossus",
    name: "Colossus",
    description:
      "First programmable (using switches and plugs) electronic digital computer, designed for codebreaking.",
    year: 1943,
    url: "https://en.wikipedia.org/wiki/Colossus_computer",
    tags: ["1940s", "hardware", "early-computing", "military"],
    dependsOn: ["turing-machine", "boolean-algebra"],
  },
  {
    id: "perceptron",
    name: "Perceptron",
    description:
      "First mathematical model of a biological neuron, laying groundwork for artificial intelligence.",
    year: 1943,
    url: "https://en.wikipedia.org/wiki/Perceptron",
    tags: ["1940s", "hardware", "artificial-intelligence"],
    dependsOn: ["boolean-algebra"],
  },
  {
    id: "eniac",
    name: "ENIAC",
    description:
      "First general-purpose, programmable (using switches and plugs) electronic digital computer, marking the start of the modern computing era.",
    year: 1945,
    url: "https://en.wikipedia.org/wiki/ENIAC",
    tags: [
      "1940s",
      "hardware",
      "early-computing",
      "mainframe",
      "military",
      "scientific",
    ],
    dependsOn: ["differential-analyzer", "abc-atanasoff-berry-computer"],
  },
  {
    id: "von-neumann-architecture",
    name: "von Neumann Architecture",
    description:
      "Established the foundational design for modern stored-program computers.",
    year: 1945,
    url: "https://en.wikipedia.org/wiki/Von_Neumann_architecture",
    tags: ["1940s", "hardware", "theoretical-foundation"],
    dependsOn: ["turing-machine", "eniac"],
  },
  {
    id: "memex",
    name: "Memex",
    description:
      "Hypothetical electromechanical device for storing and rapidly consulting a large information repository.",
    year: 1945,
    url: "https://en.wikipedia.org/wiki/Memex",
    tags: [
      "1940s",
      "human-computer-symbiosis",
      "hypermedia",
      "hardware-concept",
      "information-retrieval",
    ],
    dependsOn: [],
  },
  {
    id: "transistor",
    name: "transistor",
    description:
      "Enabled smaller, faster, and more reliable computers, revolutionizing electronics.",
    year: 1947,
    url: "https://en.wikipedia.org/wiki/History_of_the_transistor",
    tags: ["1940s", "hardware"],
    dependsOn: [],
  },
  {
    id: "manchester-baby",
    name: "Manchester Baby",
    description:
      "First stored-program computer, designed as a proof-of-concept.",
    year: 1948,
    url: "https://en.wikipedia.org/wiki/Manchester_Baby",
    tags: ["1940s", "hardware", "early-computing", "scientific"],
    dependsOn: ["von-neumann-architecture", "eniac"],
  },
  {
    id: "edsac",
    name: "EDSAC",
    description:
      "First practical stored-program computer, providing regular computing service and influencing subsequent computer designs.",
    year: 1949,
    url: "https://en.wikipedia.org/wiki/EDSAC",
    tags: ["1940s", "hardware", "early-computing", "scientific"],
    influencedBy: ["manchester-baby", "von-neumann-architecture", "eniac"],
  },
  {
    id: "erma",
    name: "ERMA",
    description:
      "Electronic Recording Machine, Accounting. Established the foundation for computerized banking and automated check processing using magnetic ink character recognition.",
    year: 1955,
    url: "https://en.wikipedia.org/wiki/ERMA",
    tags: ["1950s", "hardware", "business"],
    dependsOn: ["eniac", "transistor", "core-memory"],
  },
  {
    id: "turing-test",
    name: "Turing Test",
    description:
      "Proposed benchmark for machine intelligence, profoundly influencing AI research and public perception of machine capabilities.",
    year: 1950,
    url: "https://en.wikipedia.org/wiki/Turing_test",
    tags: ["1950s", "artificial-intelligence", "theoretical-foundation"],
    dependsOn: ["turing-machine"],
  },
  {
    id: "computer-chess",
    name: "computer chess",
    description:
      "Early challenge problem for AI, driving advances in search algorithms, parallel processing, and specialized hardware design.",
    year: 1950,
    url: "https://en.wikipedia.org/wiki/Computer_chess",
    tags: ["1950s", "artificial-intelligence", "gaming"],
    dependsOn: ["turing-machine", "boolean-algebra"],
  },
  {
    id: "core-memory",
    name: "magnetic core memory",
    description:
      "First reliable high-speed random access memory, dominating computer memory from the 1950s to 1970s.",
    year: 1951,
    tags: ["1950s", "hardware", "data-storage"],
    dependsOn: [],
  },
  {
    id: "whirlwind",
    name: "Whirlwind",
    description:
      "First real-time computer and first computer with video display output.",
    year: 1951,
    url: "https://en.wikipedia.org/wiki/Whirlwind_(computer)",
    tags: [
      "1950s",
      "hardware",
      "interactive-computing",
      "graphical-computing",
      "military",
    ],
    dependsOn: ["eniac", "manchester-baby", "core-memory"],
  },
  {
    id: "univac",
    name: "UNIVAC",
    description:
      "First commercial computer produced in the United States, marking the start of the commercial computer era.",
    year: 1951,
    url: "https://en.wikipedia.org/wiki/UNIVAC_I",
    tags: ["1950s", "hardware", "mainframe", "business"],
    dependsOn: ["eniac", "manchester-baby", "core-memory"],
  },
  {
    id: "ibm-700-7000",
    name: "IBM 700/7000 series",
    description:
      "IBM's first series of large-scale computers that dominated scientific and military computing in the 1950s and early 1960s.",
    year: "1952-1964",
    url: "https://en.wikipedia.org/wiki/IBM_700/7000_series",
    tags: [
      "1950s",
      "1960s",
      "hardware",
      "mainframe",
      "business",
      "scientific",
      "military",
    ],
    dependsOn: [
      "univac",
      "transistor",
      "core-memory",
      "von-neumann-architecture",
    ],
  },
  {
    id: "computer-science",
    name: "Computer science",
    description: "Establishment of computer science as an academic discipline.",
    year: 1953,
    url: "https://en.wikipedia.org/wiki/Computer_science#History",
    tags: ["theoretical-foundation", "education"],
    dependsOn: [
      "1950s",
      "turing-machine",
      "boolean-algebra",
      "von-neumann-architecture",
    ],
  },
  {
    id: "dartmouth-workshop",
    name: "Dartmouth Workshop",
    description:
      "Seminal conference that coined the term 'Artificial Intelligence' and launched AI as a field.",
    year: 1956,
    url: "https://en.wikipedia.org/wiki/Dartmouth_workshop",
    tags: ["1950s", "artificial-intelligence"],
    dependsOn: ["turing-machine", "perceptron"],
  },
  {
    id: "gm-os",
    name: "GM-NAA I/O",
    description:
      "One of the first operating systems, developed for the IBM 704 computer. It introduced the concept of a resident monitor program that managed I/O operations.",
    year: 1956,
    url: "https://en.wikipedia.org/wiki/GM-NAA_I/O",
    tags: ["1950s", "operating-system"],
    dependsOn: ["ibm-700-7000"],
  },
  {
    id: "tx-0",
    name: "TX-0",
    description:
      "Early transistorized computer that pioneered interactive computing concepts.",
    year: 1956,
    url: "https://en.wikipedia.org/wiki/TX-0",
    tags: ["1950s", "hardware", "time-sharing", "interactive-computing"],
    dependsOn: ["whirlwind", "transistor"],
  },
  {
    id: "ic",
    name: "integrated circuit",
    description:
      "Enabled dramatic miniaturization and cost reduction in computing devices.",
    year: 1958,
    url: "https://en.wikipedia.org/wiki/Integrated_circuit",
    tags: ["1950s", "hardware"],
    dependsOn: ["transistor"],
  },
  {
    id: "sage",
    name: "SAGE",
    description:
      "Pioneered real-time computing and large-scale networking for air defense.",
    year: 1958,
    url: "https://en.wikipedia.org/wiki/Semi-Automatic_Ground_Environment",
    tags: [
      "1950s",
      "hardware",
      "interactive-computing",
      "military",
      "networking",
    ],
    dependsOn: ["whirlwind", "tx-0"],
  },
  {
    id: "pdp-1",
    name: "PDP-1",
    description:
      "First commercial interactive computer, fostering early hacker culture.",
    year: 1959,
    url: "https://en.wikipedia.org/wiki/PDP-1",
    tags: ["1950s", "hardware", "time-sharing", "interactive-computing"],
    dependsOn: ["tx-0"],
  },
  {
    id: "mit-railroad-club",
    name: "MIT Tech Model Railroad Club",
    description:
      "Birthplace of hacker culture, influencing early computer programming.",
    year: "1950s–1960s",
    url: "https://en.wikipedia.org/wiki/Tech_Model_Railroad_Club",
    tags: [
      "1950s",
      "1960s",
      "hacker-hippie-culture",
      "time-sharing",
      "interactive-computing",
    ],
    dependsOn: ["tx-0", "pdp-1"],
  },
  {
    id: "plato",
    name: "PLATO (Programmed Logic for Automatic Teaching Operations)",
    description:
      "Pioneering computer-assisted instruction system that introduced key concepts in online community and multimedia education, including forums, message boards, online testing, email, chat rooms, picture languages, instant messaging, remote screen sharing, and multiplayer games.",
    year: 1960,
    url: "https://en.wikipedia.org/wiki/PLATO_(computer_system)",
    tags: [
      "1960s",
      "education",
      "social-computing",
      "graphical-computing",
      "interactive-computing",
      "communication",
    ],
    dependsOn: ["cdc-6600", "time-sharing"],
  },
  {
    id: "sabre",
    name: "SABRE",
    description:
      "Semi-Automated Business Research Environment. First real-time computerized reservation system.",
    year: 1960,
    url: "https://en.wikipedia.org/wiki/Sabre_(computer_system)",
    tags: ["1960s", "hardware", "business", "networking"],
    dependsOn: ["erma", "sage"],
  },
  {
    id: "ctss",
    name: "Compatible Time-Sharing System",
    description: "One of the first systems to implement time-sharing.",
    year: 1961,
    url: "https://en.wikipedia.org/wiki/Compatible_Time-Sharing_System",
    tags: ["1960s", "operating-system", "time-sharing"],
    dependsOn: ["ibm-700-7000"],
  },
  {
    id: "atlas-supervisor",
    name: "Atlas Supervisor",
    description:
      "Pioneering operating system for the Manchester Atlas computer, introducing concepts like virtual memory and paging.",
    year: 1962,
    url: "https://en.wikipedia.org/wiki/Atlas_Supervisor",
    tags: ["1960s", "operating-system"],
    dependsOn: ["manchester-baby"],
  },
  {
    id: "linc",
    name: "LINC",
    description:
      "Laboratory INstrument Computer. Allowed researchers to control their experiments and analyze data in real-time. It was designed to be operated by a single user and featured a keyboard, display, and storage system, making it one of the earliest examples of an interactive personal computer.",
    year: 1962,
    url: "https://en.wikipedia.org/wiki/LINC",
    tags: [
      "1960s",
      "hardware",
      "minicomputer",
      "interactive-computing",
      "personal-computing",
      "scientific",
    ],
    dependsOn: ["pdp-1", "tx-0"],
  },
  {
    id: "ascii",
    name: "ASCII",
    description:
      "Standardized character encoding system that became fundamental to digital text representation and communication.",
    year: 1963,
    url: "https://en.wikipedia.org/wiki/ASCII",
    tags: ["1960s", "standards", "text-processing"],
    dependsOn: [],
  },
  {
    id: "sketchpad",
    name: "Sketchpad",
    description:
      "Revolutionary computer program that pioneered human-computer interaction and computer-aided design.",
    year: 1963,
    url: "https://en.wikipedia.org/wiki/Sketchpad",
    tags: [
      "1960s",
      "human-computer-symbiosis",
      "interactive-computing",
      "graphical-computing",
    ],
    dependsOn: ["whirlwind", "tx-0"],
  },
  {
    id: "cdc-6600",
    name: "CDC 6600",
    description:
      "First successful supercomputer, introducing innovative architectural features that influenced future high-performance computer designs.",
    year: 1964,
    url: "https://en.wikipedia.org/wiki/CDC_6600",
    tags: ["1960s", "hardware", "supercomputer"],
    dependsOn: ["transistor"],
  },
  {
    id: "dartmouth-time-sharing-system",
    name: "Dartmouth Time-Sharing System",
    description:
      "One of the first time-sharing operating systems which led to the creation of BASIC.",
    year: 1964,
    url: "https://en.wikipedia.org/wiki/Dartmouth_Time_Sharing_System",
    tags: ["1960s", "operating-system", "software", "time-sharing"],
    dependsOn: ["ctss"],
  },
  {
    id: "ibm-system-360",
    name: "IBM System/360",
    description:
      "A family of mainframe computers that revolutionized the industry by introducing the concept of compatible computers of different sizes and capabilities. It allowed customers to start with a smaller system and upgrade to larger ones without rewriting software. The System/360 dominated the mainframe market for decades and influenced computer architecture well into the 21st century.",
    year: 1964,
    url: "https://en.wikipedia.org/wiki/IBM_System/360",
    tags: ["hardware", "mainframe", "business", "scientific"],
    dependsOn: ["ibm-700-7000", "atlas-supervisor"],
  },
  {
    id: "hypertext",
    name: "hypertext",
    description:
      "Concept of interlinked text documents. Formed the basis for the World Wide Web and modern digital document structures.",
    year: 1965,
    url: "https://en.wikipedia.org/wiki/Hypertext",
    tags: [
      "1960s",
      "human-computer-symbiosis",
      "hypermedia",
      "information-retrieval",
    ],
    dependsOn: ["memex"],
  },
  {
    id: "packet-switching",
    name: "Packet Switching",
    description:
      "Foundational concept for data communication in computer networks, crucial for the development of the Internet.",
    year: 1965,
    tags: ["1960s", "networking", "internet"],
    dependsOn: [],
  },
  {
    id: "pdp-8",
    name: "PDP-8",
    description:
      "First commercially successful minicomputer, making computers more accessible.",
    year: 1965,
    url: "https://en.wikipedia.org/wiki/PDP-8",
    tags: [
      "1960s",
      "hardware",
      "minicomputer",
      "time-sharing",
      "interactive-computing",
      "hardware",
    ],
    dependsOn: ["pdp-1", "linc"],
  },
  {
    id: "nls",
    name: "NLS",
    description:
      "oN-Line System. Revolutionary computer collaboration system, a precursor to modern graphical user interfaces.",
    year: 1968,
    url: "https://en.wikipedia.org/wiki/NLS_(computer_system)",
    tags: [
      "1960s",
      "human-computer-symbiosis",
      "interactive-computing",
      "hardware",
      "networking",
      "graphical-computing",
      "information-retrieval",
    ],
    dependsOn: ["sketchpad", "memex"],
  },
  {
    id: "os360",
    name: "OS/360",
    description:
      "Groundbreaking operating system for the IBM System/360 mainframe computer family, introducing features like multiprogramming and multiprocessing.",
    year: 1966,
    url: "https://en.wikipedia.org/wiki/OS/360_and_successors",
    tags: ["1960s", "operating-system"],
    dependsOn: ["ibm-system-360", "atlas-supervisor"],
  },
  {
    id: "grail",
    name: "GRAIL",
    description:
      "GRAphical Input Language. Pioneering system that introduced many concepts in pen computing and graphical user interfaces. It allowed users to create and manipulate flowcharts directly on a display screen using a light pen.",
    year: 1968,
    url: "https://en.wikipedia.org/wiki/RAND_Tablet",
    tags: [
      "1960s",
      "human-computer-symbiosis",
      "graphical-computing",
      "interactive-computing",
    ],
    dependsOn: ["sketchpad"],
  },
  {
    id: "whole-earth-catalog",
    name: "Whole Earth Catalog",
    description:
      "Countercultural magazine and product catalog that influenced early personal computer enthusiasts and entrepreneurs, connecting computing with broader social and environmental concerns.",
    year: 1968,
    url: "https://en.wikipedia.org/wiki/Whole_Earth_Catalog",
    tags: ["1960s", "hacker-hippie-culture"],
    dependsOn: [],
  },
  {
    id: "arpanet",
    name: "ARPANET",
    description: "Predecessor to the modern internet.",
    year: 1969,
    url: "https://en.wikipedia.org/wiki/ARPANET",
    tags: [
      "1960s",
      "human-computer-symbiosis",
      "social-computing",
      "networking",
      "internet",
    ],
    dependsOn: ["packet-switching"],
  },
  {
    id: "multics",
    name: "Multics",
    description:
      "Influential time-sharing operating system that introduced many concepts found in modern OSes, including hierarchical file systems and dynamic linking.",
    year: 1969,
    url: "https://en.wikipedia.org/wiki/Multics",
    tags: ["1960s", "operating-system", "time-sharing"],
    dependsOn: ["ctss"],
  },
  {
    id: "relational-database",
    name: "relational database",
    description:
      "Introduced the relational model for database management, revolutionizing data storage and retrieval in computing.",
    year: 1970,
    url: "https://en.wikipedia.org/wiki/Relational_database",
    tags: ["1970s", "database", "information-retrieval"],
    dependsOn: ["predicate-logic", "codasyl"],
  },
  {
    id: "unix",
    name: "Unix",
    description:
      "Influential operating system design, emphasizing modularity and multi-user capabilities.",
    year: 1970,
    url: "https://en.wikipedia.org/wiki/Unix",
    tags: [
      "1970s",
      "operating-system",
      "time-sharing",
      "open-source",
      "networking",
    ],
    dependsOn: ["multics", "ctss", "pdp-8"],
  },
  {
    id: "alohanet",
    name: "ALOHAnet",
    description:
      "One of the first wireless computer communication networks, developed at the University of Hawaii. ALOHAnet pioneered the use of random access protocols for shared medium networks, which became foundational for Ethernet and later Wi-Fi. It demonstrated the feasibility of wireless packet data networks and introduced concepts like exponential backoff for collision resolution.",
    year: 1971,
    url: "https://en.wikipedia.org/wiki/ALOHAnet",
    tags: ["networking", "wireless", "packet-switching"],
    dependsOn: ["arpanet"],
  },
  {
    id: "email",
    name: "Email",
    description:
      "Electronic mail system for exchanging messages over computer networks.",
    year: 1971,
    url: "https://en.wikipedia.org/wiki/Email",
    tags: ["1970s", "social-computing", "networking", "communication"],
    dependsOn: ["ctss"],
  },
  {
    id: "intel-4004",
    name: "Intel 4004",
    description:
      "The first commercially available microprocessor, marking the beginning of the microprocessor revolution. It was a 4-bit CPU designed for use in a calculator.",
    year: 1971,
    url: "https://en.wikipedia.org/wiki/Intel_4004",
    tags: ["1970s", "hardware", "microprocessor"],
    dependsOn: ["ic"],
  },
  {
    id: "dynabook",
    name: "Dynabook",
    description:
      "Early conceptualization of a personal computer optimized for learning.",
    year: 1972,
    url: "https://en.wikipedia.org/wiki/Dynabook",
    tags: [
      "1970s",
      "human-computer-symbiosis",
      "hardware-concept",
      "personal-computing",
      "portable",
      "education",
    ],
    dependsOn: ["logo", "smalltalk"],
  },
  {
    id: "intel-8008",
    name: "Intel 8008",
    description: "The first 8-bit microprocessor.",
    year: 1972,
    url: "https://en.wikipedia.org/wiki/Intel_8008",
    tags: ["1970s", "hardware", "microprocessor"],
    dependsOn: ["intel-4004"],
  },
  {
    id: "people-computer-company",
    name: "People's Computer Company",
    description:
      "Organization and associated newsletter that promoted accessible computing and computer education, influential in the early personal computer movement.",
    year: 1972,
    url: "https://en.wikipedia.org/wiki/People%27s_Computer_Company",
    tags: ["1970s", "hacker-hippie-culture", "social-computing", "education"],
    dependsOn: ["basic"],
  },
  {
    id: "community-memory",
    name: "Community Memory",
    description:
      "First public computerized bulletin board system, embodying countercultural ideals of information freedom and community empowerment through technology.",
    year: 1973,
    url: "https://en.wikipedia.org/wiki/Community_Memory",
    tags: [
      "1970s",
      "hacker-hippie-culture",
      "social-computing",
      "networking",
      "communication",
      "information-retrieval",
    ],
    dependsOn: ["arpanet"],
  },
  {
    id: "ethernet",
    name: "Ethernet",
    description:
      "Standardized local area networking technology, crucial for connected computing.",
    year: 1973,
    url: "https://en.wikipedia.org/wiki/Ethernet",
    tags: ["1970s", "social-computing", "networking"],
    dependsOn: ["alohanet", "xerox-alto"],
  },
  {
    id: "xerox-alto",
    name: "Xerox Alto",
    description:
      "Pioneered graphical user interfaces, influencing future personal computers.",
    year: 1973,
    url: "https://en.wikipedia.org/wiki/Xerox_Alto",
    tags: [
      "1970s",
      "human-computer-symbiosis",
      "social-computing",
      "personal-computing",
      "graphical-computing",
      "interactive-computing",
      "information-retrieval",
    ],
    dependsOn: ["nls", "plato", "grail", "linc", "dynabook", "email"],
  },
  {
    id: "computer-lib",
    name: "Computer Lib/Dream Machines",
    description:
      "Influential book that articulated a vision of computers as tools for creativity and personal freedom, helping to shape the personal computer revolution.",
    year: 1974,
    url: "https://en.wikipedia.org/wiki/Computer_Lib/Dream_Machines",
    tags: ["1970s", "hacker-hippie-culture", "personal-computing", "education"],
    dependsOn: ["pdp-1", "hypertext"],
  },
  {
    id: "cp-m",
    name: "CP/M",
    description:
      "Early operating system for microcomputers that influenced personal computing.",
    year: 1974,
    url: "https://en.wikipedia.org/wiki/CP/M",
    tags: ["1970s", "operating-system", "personal-computing"],
    dependsOn: ["pdp-8"],
  },
  {
    id: "intel-8080",
    name: "Intel 8080",
    description:
      "An 8-bit microprocessor that became the basis for many early personal computers and was the target CPU for the CP/M operating system.",
    year: 1974,
    url: "https://en.wikipedia.org/wiki/Intel_8080",
    tags: ["1970s", "hardware", "microprocessor"],
    dependsOn: ["intel-8008"],
  },
  {
    id: "motorola-6800",
    name: "Motorola 6800",
    description:
      "An early 8-bit microprocessor that influenced the design of many subsequent processors, including the MOS Technology 6502.",
    year: 1974,
    url: "https://en.wikipedia.org/wiki/Motorola_6800",
    tags: ["1970s", "hardware", "microprocessor"],
    dependsOn: ["intel-8008"],
  },
  {
    id: "altair",
    name: "Altair 8800",
    description:
      "First successful personal computer, launching the PC revolution.",
    year: 1975,
    url: "https://en.wikipedia.org/wiki/Altair_8800",
    tags: [
      "1970s",
      "hardware",
      "microcomputer",
      "personal-computing",
      "hacker-hippie-culture",
    ],
    dependsOn: ["pdp-8", "intel-8080"],
  },
  {
    id: "homebrew-computer-club",
    name: "Homebrew Computer Club",
    description:
      "Influential computer hobbyist group in Silicon Valley that fostered many innovations in personal computing, playing a crucial role in the development of the industry.",
    year: 1975,
    url: "https://en.wikipedia.org/wiki/Homebrew_Computer_Club",
    tags: ["1970s", "hacker-hippie-culture", "personal-computing"],
    dependsOn: ["altair"],
  },
  {
    id: "mos-6502",
    name: "MOS Technology 6502",
    description:
      "A low-cost 8-bit microprocessor that powered many popular home computers and game consoles of the 1970s and 1980s.",
    year: 1975,
    url: "https://en.wikipedia.org/wiki/MOS_Technology_6502",
    tags: ["1970s", "hardware", "microprocessor"],
    dependsOn: ["motorola-6800"],
  },
  {
    id: "apple1",
    name: "Apple I",
    description:
      "Pioneered pre-assembled personal computers, helping popularize home computing.",
    year: 1976,
    url: "https://en.wikipedia.org/wiki/Apple_I",
    tags: ["1970s", "hardware", "microcomputer", "personal-computing"],
    dependsOn: [
      "altair",
      "homebrew-computer-club",
      "whole-earth-catalog",
      "mos-6502",
    ],
  },
  {
    id: "cray-1",
    name: "Cray-1",
    description:
      "Groundbreaking supercomputer that set new standards for processing speed and influenced high-performance computing design.",
    year: 1976,
    url: "https://en.wikipedia.org/wiki/Cray-1",
    tags: ["1970s", "hardware", "supercomputer"],
    dependsOn: ["cdc-6600"],
  },
  {
    id: "zilog-z80",
    name: "Zilog Z80",
    description:
      "An 8-bit microprocessor that improved upon the Intel 8080 and became widely used in many home computers, embedded systems, and the Nintendo Game Boy.",
    year: 1976,
    url: "https://en.wikipedia.org/wiki/Zilog_Z80",
    tags: ["1970s", "hardware", "microprocessor"],
    dependsOn: ["intel-8080"],
  },
  {
    id: "apple2",
    name: "Apple II",
    description:
      "One of the first highly successful mass-produced personal computers.",
    year: 1977,
    url: "https://en.wikipedia.org/wiki/Apple_II",
    tags: ["1970s", "hardware", "microcomputer", "personal-computing"],
    dependsOn: ["apple1", "xerox-alto"],
  },
  {
    id: "commodore-pet",
    name: "Commodore PET",
    description:
      "One of the first personal computers aimed at the home and education markets.",
    year: 1977,
    url: "https://en.wikipedia.org/wiki/Commodore_PET",
    tags: ["1970s", "hardware", "microcomputer", "personal-computing"],
    dependsOn: ["apple2", "mos-6502"],
  },
  {
    id: "trs80",
    name: "TRS-80",
    description:
      "One of the earliest mass-produced personal computers, bringing computing to homes and small businesses.",
    year: 1977,
    url: "https://en.wikipedia.org/wiki/TRS-80",
    tags: ["1970s", "hardware", "microcomputer", "personal-computing"],
    dependsOn: ["altair", "zilog-z80"],
  },
  {
    id: "bsd",
    name: "BSD",
    description:
      "Berkeley Software Distribution. Unix derivative that played a crucial role in the development of the internet and introduced key networking technologies.",
    year: 1977,
    url: "https://en.wikipedia.org/wiki/Berkeley_Software_Distribution",
    tags: ["1970s", "operating-system", "open-source", "networking"],
    dependsOn: ["unix"],
  },
  {
    id: "vms",
    name: "VAX/VMS",
    description:
      "Operating system for DEC minicomputers that pioneered features like clustering and hierarchical file system with versioning.",
    year: 1977,
    url: "https://en.wikipedia.org/wiki/OpenVMS",
    tags: ["1970s", "operating-system"],
    dependsOn: ["multics"],
  },
  {
    id: "cbbs",
    name: "CBBS",
    description:
      "Computerized Bulletin Board System. Precursor to online forums and social media.",
    year: 1978,
    url: "https://en.wikipedia.org/wiki/CBBS",
    tags: ["1970s", "social-computing", "networking", "communication"],
    dependsOn: ["community-memory"],
  },
  {
    id: "gps",
    name: "GPS",
    description:
      "Global Positioning System. Satellite-based navigation system that enabled modern location-based technologies.",
    year: 1978,
    tags: ["1970s", "networking", "military"],
    dependsOn: [],
  },
  {
    id: "intel-8086",
    name: "Intel 8086",
    description:
      "Intel's first 16-bit microprocessor, which became the foundation for the IBM PC and the dominant architecture in personal computing.",
    year: 1978,
    url: "https://en.wikipedia.org/wiki/Intel_8086",
    tags: ["1970s", "hardware", "microprocessor"],
    dependsOn: ["intel-8080"],
  },
  {
    id: "motorola-68000",
    name: "Motorola 68000",
    description:
      "A 16/32-bit microprocessor that powered many influential computer systems, including the original Apple Macintosh, Amiga, and early Unix workstations.",
    year: 1979,
    url: "https://en.wikipedia.org/wiki/Motorola_68000",
    tags: ["1970s", "hardware", "microprocessor"],
    dependsOn: ["motorola-6800"],
  },
  {
    id: "visicalc",
    name: "VisiCalc",
    description:
      "First spreadsheet program, demonstrating the business potential of personal computers.",
    year: 1979,
    url: "https://en.wikipedia.org/wiki/VisiCalc",
    tags: ["1970s", "software", "business", "personal-computing"],
    dependsOn: ["apple2", "trs80"],
  },
  {
    id: "qdos",
    name: "QDOS",
    description:
      "Operating system developed by Tim Paterson, which was purchased by Microsoft and became the basis for MS-DOS.",
    year: 1980,
    url: "https://en.wikipedia.org/wiki/86-DOS",
    tags: ["1980s", "operating-system"],
    dependsOn: ["cp-m"],
  },
  {
    id: "usenet",
    name: "Usenet",
    description:
      "Decentralized discussion system, precursor to internet forums.",
    year: 1980,
    url: "https://en.wikipedia.org/wiki/Usenet",
    tags: ["1980s", "social-computing", "communication", "networking"],
    dependsOn: ["unix", "cbbs", "email"],
  },
  {
    id: "ibm-pc",
    name: "IBM PC",
    description:
      "Standardized the PC industry, leading to widespread adoption of compatible systems.",
    year: 1981,
    url: "https://en.wikipedia.org/wiki/IBM_Personal_Computer",
    tags: ["1980s", "hardware", "personal-computing", "hardware"],
    dependsOn: [
      "apple2",
      "trs80",
      "commodore-pet",
      "intel-8086",
      "ibm-system-360",
    ],
  },
  {
    id: "ms-dos",
    name: "MS-DOS",
    description:
      "Operating system for IBM PCs and compatibles, dominating the personal computer market throughout the 1980s.",
    year: 1981,
    url: "https://en.wikipedia.org/wiki/MS-DOS",
    tags: ["1980s", "operating-system", "software", "personal-computing"],
    dependsOn: ["qdos"],
  },
  {
    id: "bbc-micro",
    name: "BBC Micro",
    description:
      "Series of microcomputers and associated peripherals designed and built by Acorn Computers for the BBC Computer Literacy Project. Its success led Acorn to develop the ARM architecture.",
    year: 1981,
    url: "https://en.wikipedia.org/wiki/BBC_Micro",
    tags: ["1980s", "hardware", "personal-computing", "education"],
    dependsOn: ["apple2", "commodore-pet"],
  },
  {
    id: "risc",
    name: "RISC",
    description:
      "Reduced Instruction Set Computing. Simplified processor design philosophy that led to more efficient and scalable CPUs, influencing modern processor designs.",
    year: 1981,
    url: "https://en.wikipedia.org/wiki/Reduced_instruction_set_computer",
    tags: ["1980s", "hardware", "microprocessor"],
    dependsOn: ["ibm-801", "ibm-system-360"],
  },
  {
    id: "compaq-portable",
    name: "Compaq Portable",
    description:
      "First IBM PC compatible computer that was reverse-engineered to be fully compatible with IBM's proprietary BIOS, effectively creating the PC clone market and accelerating the standardization of the PC platform.",
    year: 1982,
    url: "https://en.wikipedia.org/wiki/Compaq_Portable",
    tags: ["1980s", "hardware", "personal-computing", "portable"],
    dependsOn: ["ibm-pc"],
  },
  {
    id: "minitel",
    name: "Minitel",
    description:
      "French videotex online service accessible through telephone lines, predating the World Wide Web as a widely available online information system.",
    year: 1982,
    url: "https://en.wikipedia.org/wiki/Minitel",
    tags: ["1980s", "networking", "communication"],
    dependsOn: ["arpanet"],
  },
  {
    id: "apple-lisa",
    name: "Apple Lisa",
    description:
      "One of the first personal computers to feature a graphical user interface and mouse, pioneering several GUI concepts that would become standard in future systems.",
    year: 1983,
    url: "https://en.wikipedia.org/wiki/Apple_Lisa",
    tags: ["1980s", "hardware", "personal-computing", "graphical-computing"],
    dependsOn: ["xerox-alto", "apple2", "motorola-68000"],
  },
  {
    id: "gnu",
    name: "GNU Project",
    description:
      "Pioneered the free software movement, leading to open-source development.",
    year: 1983,
    url: "https://en.wikipedia.org/wiki/GNU_Project",
    tags: ["1980s", "hacker-hippie-culture", "open-source", "software"],
    dependsOn: ["unix"],
  },
  {
    id: "tcp-ip",
    name: "TCP/IP",
    description:
      "Foundational protocols of the Internet, enabling diverse computer hardware to interconnect and communicate.",
    year: 1983,
    url: "https://en.wikipedia.org/wiki/Internet_protocol_suite",
    tags: ["1980s", "social-computing", "networking", "internet"],
    dependsOn: ["arpanet"],
  },
  {
    id: "boxer",
    name: "Boxer",
    description:
      "Educational computing environment that combined visual programming concepts with a spatial metaphor for program organization, influenced by LOGO and Smalltalk but emphasizing naive realism and spatial metaphors.",
    year: 1984,
    url: "https://en.wikipedia.org/wiki/Boxer_(programming_language)",
    tags: [
      "1980s",
      "education",
      "programming-language",
      "graphical-computing",
      "interactive-computing",
    ],
    dependsOn: ["logo", "smalltalk", "lisp"],
  },
  {
    id: "macintosh",
    name: "Macintosh",
    description:
      "First successful mass-market computer with a graphical user interface.",
    year: 1984,
    url: "https://en.wikipedia.org/wiki/Macintosh",
    tags: ["1980s", "hardware", "personal-computing", "graphical-computing"],
    dependsOn: ["apple2", "apple-lisa", "motorola-68000"],
  },
  {
    id: "arm1",
    name: "ARM1",
    description:
      "Laid the foundation for the ARM architecture that would later dominate mobile and embedded computing.",
    year: 1985,
    url: "https://en.wikipedia.org/wiki/ARM_architecture#ARM1",
    tags: ["1980s", "hardware", "microprocessor"],
    dependsOn: ["risc", "bbc-micro"],
  },
  {
    id: "windows",
    name: "Windows",
    description:
      "Standardized the GUI for mass-market computers, becoming the dominant PC operating system.",
    year: 1985,
    url: "https://en.wikipedia.org/wiki/Microsoft_Windows",
    tags: ["1980s", "operating-system", "software", "personal-computing"],
    dependsOn: ["macintosh", "ms-dos"],
  },
  {
    id: "laserwriter",
    name: "LaserWriter",
    description:
      "First laser printer with built-in PostScript, key to desktop publishing revolution.",
    year: 1985,
    url: "https://en.wikipedia.org/wiki/LaserWriter",
    tags: ["1980s", "hardware", "desktop-publishing"],
    dependsOn: ["macintosh", "xerox-alto"],
  },
  {
    id: "mach",
    name: "Mach",
    description:
      "First microkernel, influential in operating system design for its modular architecture and innovative features like inter-process communication and memory management.",
    year: 1985,
    url: "https://en.wikipedia.org/wiki/Mach_(kernel)",
    tags: ["1980s", "operating-system"],
    influencedBy: ["bsd"],
  },
  {
    id: "hypercard",
    name: "HyperCard",
    description:
      "Hypermedia authoring tool widely used for creating custom applications on the Macintosh. Influenced later developments, notably the World Wide Web.",
    year: 1987,
    url: "https://en.wikipedia.org/wiki/HyperCard",
    tags: [
      "1980s",
      "software",
      "hypermedia",
      "information-retrieval",
      "multimedia",
    ],
    dependsOn: ["macintosh"],
  },
  {
    id: "knowledge-navigator",
    name: "Knowledge Navigator",
    description:
      "Apple's hardware-concept future computer with natural language processing and augmented reality.",
    year: 1987,
    url: "https://en.wikipedia.org/wiki/Knowledge_Navigator",
    tags: [
      "1980s",
      "hardware-concept",
      "artificial-intelligence",
      "information-retrieval",
    ],
    dependsOn: ["hypercard", "dynabook"],
  },
  {
    id: "minix",
    name: "MINIX",
    description:
      "Unix-like operating system created by Andrew S. Tanenbaum for educational purposes, which significantly influenced the design of Linux.",
    year: 1987,
    url: "https://en.wikipedia.org/wiki/MINIX",
    tags: ["1980s", "operating-system", "education", "open-source"],
    dependsOn: ["unix"],
  },
  {
    id: "os2",
    name: "OS/2",
    description:
      "Advanced multitasking operating system initially developed as a joint project between IBM and Microsoft, later continued by IBM alone. Its development influenced Microsoft's approach to Windows NT.",
    year: 1987,
    url: "https://en.wikipedia.org/wiki/OS/2",
    tags: ["1980s", "operating-system"],
    dependsOn: ["msdos", "windows"],
  },
  {
    id: "photoshop",
    name: "Photoshop",
    description:
      "Graphics editor that revolutionized digital image manipulation and graphic design.",
    year: 1988,
    url: "https://en.wikipedia.org/wiki/Adobe_Photoshop",
    tags: ["1980s", "software", "graphical-computing"],
    dependsOn: ["macintosh"],
  },
  {
    id: "nextstep",
    name: "NeXTSTEP",
    description:
      "Object-oriented, multitasking operating system that introduced many innovative features and later formed the foundation for macOS and iOS.",
    year: 1989,
    url: "https://en.wikipedia.org/wiki/NeXTSTEP",
    tags: [
      "1980s",
      "operating-system",
      "personal-computing",
      "education",
      "scientific",
    ],
    dependsOn: ["mach", "bsd", "macintosh"],
  },
  {
    id: "www",
    name: "World Wide Web",
    description:
      "Information system enabling documents and other resources to be accessed over the Internet using hypertext.",
    year: 1989,
    url: "https://en.wikipedia.org/wiki/World_Wide_Web",
    tags: [
      "1980s",
      "web",
      "hypermedia",
      "social-computing",
      "internet",
      "networking",
    ],
    dependsOn: ["tcp-ip", "nextstep", "hypercard", "usenet"],
  },
  {
    id: "linux",
    name: "Linux",
    description:
      "Open-source Unix-like operating system kernel, powering a vast array of devices and servers.",
    year: 1991,
    url: "https://en.wikipedia.org/wiki/Linux",
    tags: ["1990s", "software", "operating-system", "open-source"],
    dependsOn: ["minix", "gnu"],
  },
  {
    id: "unicode",
    name: "Unicode",
    description:
      "Universal character encoding standard designed to support the worldwide interchange, processing, and display of written texts in diverse languages and technical disciplines.",
    year: 1991,
    url: "https://en.wikipedia.org/wiki/Unicode",
    tags: ["1990s", "standards", "text-processing"],
    dependsOn: ["ascii", "iso-8859"],
  },
  {
    id: "apple-newton",
    name: "Apple Newton",
    description:
      "Pioneering personal digital assistant (PDA) that introduced handwriting recognition and coined the term 'app' for mobile applications.",
    year: 1993,
    url: "https://en.wikipedia.org/wiki/Apple_Newton",
    tags: ["1990s", "mobile", "personal-computing"],
    dependsOn: ["dynabook", "knowledge-navigator", "self", "smalltalk"],
  },
  {
    id: "windows-nt",
    name: "Windows NT",
    description:
      "A family of operating systems produced by Microsoft, designed for high-end business and enterprise environments. Windows NT introduced a new kernel that provided true preemptive multitasking, multiprocessing, and 32-bit computing.",
    year: 1993,
    url: "https://en.wikipedia.org/wiki/Windows_NT",
    tags: ["1990s", "operating-system", "business", "personal-computing"],
    dependsOn: ["windows", "os2", "vms", "unix"],
  },
  {
    id: "magic-cap",
    name: "Magic Cap",
    description:
      "One of the first operating systems designed for mobile devices and PDAs.",
    year: 1994,
    url: "https://en.wikipedia.org/wiki/Magic_Cap",
    tags: ["1990s", "mobile", "operating-system"],
    dependsOn: ["knowledge-navigator", "hypercard"],
  },
  {
    id: "wikiwikiweb",
    name: "WikiWikiWeb",
    description:
      "First wiki. Introduced the concept of user-editable websites, leading to collaborative online content creation platforms like Wikipedia.",
    year: 1995,
    url: "https://en.wikipedia.org/wiki/WikiWikiWeb",
    tags: ["web", "social-computing", "information-retrieval"],
    dependsOn: ["www", "hypercard"],
  },
  {
    id: "google",
    name: "Google",
    description:
      "Web search engine that became a dominant force in Internet services and advertising.",
    year: 1998,
    url: "https://en.wikipedia.org/wiki/Google",
    tags: ["1990s", "web", "artificial-intelligence"],
    dependsOn: ["www"],
  },
  {
    id: "wi-fi",
    name: "Wi-Fi",
    description:
      "Wireless networking technology that became ubiquitous in mobile and home computing.",
    year: 1998,
    tags: ["1990s", "networking", "wireless"],
    dependsOn: ["ethernet"],
  },
  {
    id: "baidu",
    name: "Baidu",
    description:
      "Chinese web services company that developed one of the world's largest search engines and pioneered Chinese language internet services and AI applications.",
    year: 2000,
    url: "https://en.wikipedia.org/wiki/Baidu",
    tags: ["2000s", "web", "artificial-intelligence"],
    dependsOn: ["google"],
  },
  {
    id: "ipod",
    name: "iPod",
    description:
      "Portable media player developed by Apple that revolutionized the digital music industry and laid the groundwork for Apple's future mobile devices.",
    year: 2001,
    url: "https://en.wikipedia.org/wiki/IPod",
    tags: ["2000s", "hardware", "personal-computing", "mobile"],
    dependsOn: ["macintosh", "mp3"],
  },
  {
    id: "macosx",
    name: "Mac OS X",
    description:
      "Unix-based operating system that modernized Apple's desktop OS, combining powerful Unix underpinnings with an intuitive user interface, setting the foundation for Apple's modern computing platforms.",
    year: 2001,
    url: "https://en.wikipedia.org/wiki/MacOS",
    tags: ["2000s", "operating-system", "personal-computing"],
    dependsOn: ["nextstep", "gnu", "macintosh", "wi-fi"],
  },
  {
    id: "wikipedia",
    name: "Wikipedia",
    description:
      "Free, collaborative, multilingual online encyclopedia that revolutionized the creation and distribution of knowledge.",
    year: 2001,
    url: "https://en.wikipedia.org/wiki/Wikipedia",
    tags: ["2000s", "web", "information-retrieval"],
    dependsOn: ["www", "usenet", "wikiwikiweb"],
  },
  {
    id: "aws",
    name: "Amazon Web Services",
    description: "Pioneered cloud computing services.",
    year: 2006,
    url: "https://en.wikipedia.org/wiki/Amazon_Web_Services",
    tags: ["2000s", "internet", "web", "time-sharing"],
    dependsOn: ["www"],
  },
  {
    id: "iphone",
    name: "iPhone",
    description:
      "Pioneered the modern smartphone, revolutionizing mobile computing and app ecosystems.",
    year: 2007,
    url: "https://en.wikipedia.org/wiki/IPhone",
    tags: ["2000s", "hardware", "mobile"],
    dependsOn: ["arm1", "ipod", "macintosh", "macosx", "www", "gps"],
  },
  {
    id: "android",
    name: "Android",
    description:
      "Mobile operating system based on a modified version of the Linux kernel, dominating the smartphone market.",
    year: 2008,
    url: "https://en.wikipedia.org/wiki/Android_(operating_system)",
    tags: ["2000s", "mobile", "software", "operating-system"],
    dependsOn: ["linux", "iphone", "www"],
  },
  {
    id: "blockchain",
    name: "Blockchain",
    description:
      "Decentralized, distributed ledger technology underlying cryptocurrencies and other applications.",
    year: 2008,
    tags: ["2000s", "cryptography"],
    dependsOn: [],
  },
  {
    id: "raspberry-pi",
    name: "Raspberry Pi",
    description:
      "Series of small single-board computers developed to promote teaching of basic computer science.",
    year: 2012,
    url: "https://en.wikipedia.org/wiki/Raspberry_Pi",
    tags: ["2010s", "hardware", "education"],
    dependsOn: ["arm1", "linux"],
  },
  {
    id: "alexa",
    name: "Alexa",
    description:
      "Virtual assistant AI technology, popularizing voice-controlled smart home devices.",
    year: 2014,
    url: "https://en.wikipedia.org/wiki/Amazon_Alexa",
    tags: ["2010s", "hardware", "artificial-intelligence", "iot"],
    dependsOn: ["www"],
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    description:
      "Large language model chatbot demonstrating advanced natural language processing capabilities.",
    year: 2022,
    url: "https://en.wikipedia.org/wiki/ChatGPT",
    tags: ["2010s", "artificial-intelligence"],
    dependsOn: ["www", "wikipedia"],
  },
];

const progLangNodes = [
  {
    id: "flowmatic",
    name: "FLOW-MATIC",
    description:
      "Pioneered English-like syntax for data processing, laying the groundwork for business-oriented languages and influencing the development of COBOL.",
    year: 1955,
    url: "https://en.wikipedia.org/wiki/FLOW-MATIC",
    tags: ["1950s", "programming-language", "business", "text-processing"],
    dependsOn: [],
  },
  {
    id: "comit",
    name: "COMIT",
    description:
      "One of the earliest string processing languages, influential in the development of later pattern matching and text processing languages.",
    year: 1957,
    url: "https://en.wikipedia.org/wiki/COMIT",
    tags: ["1950s", "programming-language", "text-processing"],
    dependsOn: ["ibm-700-7000"],
  },
  {
    id: "fortran",
    name: "FORTRAN",
    description:
      "First high-level language for scientific computing, revolutionizing the field by making complex calculations more accessible to scientists and engineers.",
    year: 1957,
    url: "https://en.wikipedia.org/wiki/Fortran",
    tags: ["1950s", "programming-language", "scientific"],
    dependsOn: ["ibm-700-7000"],
  },
  {
    id: "algol",
    name: "ALGOL",
    description:
      "Introduced fundamental concepts like block structure and lexical scope, heavily influencing the design of many subsequent programming languages.",
    year: 1958,
    url: "https://en.wikipedia.org/wiki/ALGOL",
    tags: [
      "1950s",
      "programming-language",
      "general-purpose-language",
      "scientific",
    ],
    dependsOn: ["fortran"],
  },
  {
    id: "lisp",
    name: "LISP",
    description:
      "Pioneered key concepts in computer science and artificial intelligence, becoming the dominant language for AI research for decades.",
    year: 1958,
    url: "https://en.wikipedia.org/wiki/Lisp_(programming_language)",
    tags: [
      "1950s",
      "programming-language",
      "artificial-intelligence",
      "text-processing",
    ],
    dependsOn: ["predicate-logic", "ibm-700-7000", "ipl"],
  },
  {
    id: "cobol",
    name: "COBOL",
    description:
      "Standardized business-oriented computing, becoming the dominant language for commercial data processing for several decades.",
    year: 1959,
    url: "https://en.wikipedia.org/wiki/COBOL",
    tags: ["1950s", "programming-language", "business", "text-processing"],
    dependsOn: ["flowmatic"],
  },
  {
    id: "apl",
    name: "APL",
    description:
      "Introduced array programming and innovative notation, influencing later languages in scientific computing and data analysis.",
    year: 1962,
    url: "https://en.wikipedia.org/wiki/APL_(programming_language)",
    tags: ["1960s", "programming-language", "scientific"],
    dependsOn: [],
  },
  {
    id: "snobol",
    name: "SNOBOL",
    description:
      "Specialized in string manipulation, introducing advanced pattern matching features that influenced later text processing languages.",
    year: 1962,
    url: "https://en.wikipedia.org/wiki/SNOBOL",
    tags: ["1960s", "programming-language", "text-processing"],
    dependsOn: ["comit"],
  },
  {
    id: "cpl",
    name: "CPL (Combined Programming Language)",
    description:
      "Ambitious multi-purpose language that, while not widely used, significantly influenced BCPL and the subsequent B and C languages.",
    year: 1963,
    url: "https://en.wikipedia.org/wiki/CPL_(programming_language)",
    tags: ["1960s", "programming-language", "general-purpose-language"],
    dependsOn: ["algol", "fortran"],
  },
  {
    id: "basic",
    description:
      "Democratized programming by providing an easy-to-learn language, playing a crucial role in the personal computer revolution.",
    year: 1964,
    url: "https://en.wikipedia.org/wiki/BASIC",
    tags: [
      "1960s",
      "programming-language",
      "education",
      "general-purpose-language",
    ],
    dependsOn: ["fortran", "algol", "dartmouth-time-sharing-system"],
  },
  {
    id: "pl1",
    name: "PL/I",
    description:
      "Ambitious general-purpose language that attempted to combine features from FORTRAN, COBOL, and ALGOL, influencing later language designs despite limited adoption.",
    year: 1964,
    url: "https://en.wikipedia.org/wiki/PL/I",
    tags: [
      "1960s",
      "programming-language",
      "general-purpose-language",
      "business",
    ],
    dependsOn: ["fortran", "cobol", "algol"],
  },
  {
    id: "bcpl",
    name: "BCPL",
    description:
      "Precursor to B and C, introduced the concept of typeless programming and influenced the syntax of many subsequent languages.",
    year: 1967,
    url: "https://en.wikipedia.org/wiki/BCPL",
    tags: ["1960s", "programming-language", "systems-language"],
    dependsOn: ["cpl"],
  },
  {
    id: "logo",
    name: "Logo",
    description:
      "Educational language that introduced turtle graphics, significantly impacting computer science education and early graphical programming.",
    year: 1967,
    url: "https://en.wikipedia.org/wiki/Logo_(programming_language)",
    tags: ["1960s", "programming-language", "graphical-computing", "education"],
    dependsOn: ["lisp"],
  },
  {
    id: "simula",
    name: "Simula",
    description:
      "Introduced object-oriented programming concepts, profoundly influencing software design and paving the way for languages like Smalltalk and C++.",
    year: 1967,
    url: "https://en.wikipedia.org/wiki/Simula",
    tags: [
      "1960s",
      "programming-language",
      "general-purpose-language",
      "scientific",
    ],
    dependsOn: ["algol"],
  },
  {
    id: "b",
    name: "B",
    description:
      "Predecessor to C, simplified BCPL and introduced many features that influenced C's design.",
    year: 1969,
    url: "https://en.wikipedia.org/wiki/B_(programming_language)",
    tags: ["1960s", "programming-language", "systems-language"],
    dependsOn: ["bcpl"],
  },
  {
    id: "planner",
    name: "Planner",
    description:
      "Early AI language that introduced concepts like pattern-directed invocation and backtracking, influencing later logic programming languages.",
    year: 1969,
    url: "https://en.wikipedia.org/wiki/Planner_(programming_language)",
    tags: ["1960s", "programming-language", "artificial-intelligence"],
    dependsOn: ["lisp"],
  },
  {
    id: "setl",
    name: "SETL",
    description:
      "High-level language based on set theory, influential in language design and compiler construction.",
    year: 1969,
    url: "https://en.wikipedia.org/wiki/SETL",
    tags: ["1960s", "programming-language", "general-purpose-language"],
    dependsOn: ["algol"],
  },
  {
    id: "pascal",
    name: "Pascal",
    description:
      "Emphasized structured programming and became widely used in education, influencing many subsequent languages.",
    year: 1970,
    url: "https://en.wikipedia.org/wiki/Pascal_(programming_language)",
    tags: [
      "1970s",
      "programming-language",
      "education",
      "general-purpose-language",
    ],
    dependsOn: ["algol", "simula"],
  },
  {
    id: "c",
    name: "C",
    description:
      "Revolutionized systems programming, becoming the foundation for operating systems, embedded systems, and numerous other languages.",
    year: 1972,
    url: "https://en.wikipedia.org/wiki/C_(programming_language)",
    tags: [
      "1970s",
      "programming-language",
      "systems-language",
      "general-purpose-language",
    ],
    dependsOn: ["b"],
  },
  {
    id: "smalltalk",
    name: "Smalltalk",
    description:
      "Pioneered object-oriented programming and graphical user interfaces, influencing modern software development practices.",
    year: 1972,
    url: "https://en.wikipedia.org/wiki/Smalltalk",
    tags: [
      "1970s",
      "human-computer-symbiosis",
      "programming-language",
      "general-purpose-language",
      "graphical-computing",
      "education",
    ],
    dependsOn: ["xerox-alto", "grail", "simula", "lisp", "logo"],
  },
  {
    id: "prolog",
    name: "Prolog",
    description:
      "Introduced logic programming, becoming a cornerstone of artificial intelligence research and natural language processing.",
    year: 1972,
    url: "https://en.wikipedia.org/wiki/Prolog",
    tags: ["1970s", "programming-language", "artificial-intelligence"],
    dependsOn: ["predicate-logic", "lisp", "planner"],
  },
  {
    id: "ml",
    name: "ML",
    description:
      "Pioneered static typing and type inference in functional programming, influencing many modern programming languages.",
    year: 1973,
    url: "https://en.wikipedia.org/wiki/ML_(programming_language)",
    tags: [
      "1970s",
      "programming-language",
      "general-purpose-language",
      "artificial-intelligence",
    ],
    dependsOn: ["lisp"],
  },
  {
    id: "sql",
    name: "SQL",
    description:
      "Standardized database querying and management, becoming the universal language for relational databases.",
    year: 1974,
    url: "https://en.wikipedia.org/wiki/SQL",
    tags: [
      "1970s",
      "programming-language",
      "business",
      "information-retrieval",
      "database",
    ],
    dependsOn: ["predicate-logic", "relational-database", "alpha"],
  },
  {
    id: "modula",
    name: "Modula",
    description:
      "Successor to Pascal, introducing the concept of separate compilation and modules.",
    year: 1975,
    url: "https://en.wikipedia.org/wiki/Modula",
    tags: ["1970s", "programming-language", "general-purpose-language"],
    dependsOn: ["pascal", "algol"],
  },
  {
    id: "scheme",
    name: "Scheme",
    description:
      "Simplified and clarified the ideas in Lisp, becoming influential in programming language theory and computer science education.",
    year: 1975,
    url: "https://en.wikipedia.org/wiki/Scheme_(programming_language)",
    tags: [
      "1970s",
      "programming-language",
      "general-purpose-language",
      "education",
    ],
    dependsOn: ["lisp"],
  },
  {
    id: "mesa",
    name: "Mesa",
    description:
      "Systems programming language developed at Xerox PARC for the Alto and other workstations, pioneering concepts in modular programming and influencing Ada, Modula-2, and Cedar.",
    year: 1976,
    url: "https://en.wikipedia.org/wiki/Mesa_(programming_language)",
    tags: ["1970s", "programming-language", "systems-language"],
    dependsOn: ["xerox-alto", "pascal", "simula"],
  },
  {
    id: "s",
    name: "S",
    description:
      "Statistical programming language that laid the foundation for R, revolutionizing statistical computing and data analysis.",
    year: 1976,
    url: "https://en.wikipedia.org/wiki/S_(programming_language)",
    tags: ["1970s", "programming-language", "scientific"],
    dependsOn: ["apl", "fortran"],
  },
  {
    id: "awk",
    name: "AWK",
    description:
      "Text-processing language that became a staple in Unix environments, influencing many subsequent scripting languages.",
    year: 1977,
    url: "https://en.wikipedia.org/wiki/AWK",
    tags: [
      "1970s",
      "programming-language",
      "text-processing",
      "scripting-language",
    ],
    dependsOn: [],
  },
  {
    id: "shell",
    name: "Bourne shell",
    description:
      "Introduced modern shell scripting concepts, including control structures and variables, influencing subsequent shells and scripting languages.",
    year: 1977,
    url: "https://en.wikipedia.org/wiki/Bourne_shell",
    tags: ["1970s", "programming-language", "scripting-language"],
    dependsOn: ["algol"],
  },
  {
    id: "icon",
    name: "Icon",
    description:
      "High-level, general-purpose language with a focus on string and structure processing, descended from SNOBOL.",
    year: 1977,
    url: "https://en.wikipedia.org/wiki/Icon_(programming_language)",
    tags: [
      "1970s",
      "programming-language",
      "text-processing",
      "general-purpose-language",
    ],
    dependsOn: ["snobol"],
  },
  {
    id: "ada",
    name: "Ada",
    description:
      "Developed for embedded and real-time systems, particularly in defense and aerospace, emphasizing reliability and maintainability.",
    year: 1980,
    url: "https://en.wikipedia.org/wiki/Ada_(programming_language)",
    tags: [
      "1980s",
      "programming-language",
      "systems-language",
      "general-purpose-language",
    ],
    dependsOn: ["pascal", "algol"],
  },
  {
    id: "hope",
    name: "Hope",
    description:
      "One of the earliest functional programming languages, pioneering the use of lazy evaluation and influencing later functional languages.",
    year: 1980,
    url: "https://en.wikipedia.org/wiki/Hope_(programming_language)",
    tags: ["1980s", "programming-language", "general-purpose-language"],
    dependsOn: ["ml"],
  },
  {
    id: "beta",
    name: "BETA",
    description:
      "Object-oriented programming language introducing the pattern concept as a unified abstraction for objects, procedures, functions, and types, influencing design patterns and aspect-oriented programming.",
    year: 1983,
    url: "https://en.wikipedia.org/wiki/BETA_(programming_language)",
    tags: ["1980s", "programming-language", "general-purpose-language"],
    dependsOn: ["simula", "smalltalk", "modula"],
  },
  {
    id: "matlab",
    name: "MATLAB",
    description:
      "Numerical computing environment that became standard in scientific and engineering fields, influencing scientific programming and data visualization.",
    year: 1984,
    url: "https://en.wikipedia.org/wiki/MATLAB",
    tags: ["1980s", "programming-language", "scientific"],
    dependsOn: ["fortran", "apl", "s"],
  },
  {
    id: "objective-c",
    name: "Objective-C",
    description:
      "Extended C with Smalltalk-style messaging, becoming the primary language for Apple's ecosystems until the introduction of Swift.",
    year: 1984,
    url: "https://en.wikipedia.org/wiki/Objective-C",
    tags: [
      "1980s",
      "programming-language",
      "general-purpose-language",
      "systems-language",
    ],
    dependsOn: ["c", "smalltalk"],
  },
  {
    id: "c++",
    name: "C++",
    description:
      "Extended C with object-oriented features, becoming one of the most widely used programming languages in history.",
    year: 1985,
    url: "https://en.wikipedia.org/wiki/C%2B%2B",
    tags: [
      "1980s",
      "programming-language",
      "general-purpose-language",
      "systems-language",
    ],
    dependsOn: ["c", "simula"],
  },
  {
    id: "miranda",
    name: "Miranda",
    description:
      "Pure functional programming language that significantly influenced the design of Haskell.",
    year: 1985,
    url: "https://en.wikipedia.org/wiki/Miranda_(programming_language)",
    tags: ["1980s", "programming-language", "general-purpose-language"],
    dependsOn: ["ml", "hope"],
  },
  {
    id: "erlang",
    name: "Erlang",
    description:
      "Designed for building scalable, fault-tolerant systems, pioneering the actor model for concurrent programming.",
    year: 1986,
    url: "https://en.wikipedia.org/wiki/Erlang_(programming_language)",
    tags: [
      "1980s",
      "programming-language",
      "concurrent-language",
      "systems-language",
      "general-purpose-language",
    ],
    dependsOn: ["prolog"],
  },
  {
    id: "oberon",
    name: "Oberon",
    description:
      "Successor to Modula-2, emphasizing simplicity and introducing type extension.",
    year: 1986,
    url: "https://en.wikipedia.org/wiki/Oberon_(programming_language)",
    tags: ["1980s", "programming-language", "systems-language"],
    dependsOn: ["modula"],
  },
  {
    id: "abc",
    name: "ABC",
    description:
      "Teaching language that was a major influence on Python's design.",
    year: 1987,
    url: "https://en.wikipedia.org/wiki/ABC_(programming_language)",
    tags: ["1980s", "programming-language", "education"],
    dependsOn: ["setl"],
  },
  {
    id: "hypertalk",
    name: "HyperTalk",
    description:
      "Scripting language used in Apple's HyperCard, influential in popularizing the concept of hypermedia and easy-to-use programming environments.",
    year: 1987,
    url: "https://en.wikipedia.org/wiki/HyperTalk",
    tags: ["1980s", "programming-language", "scripting-language"],
    dependsOn: ["pascal", "hypercard"],
  },
  {
    id: "perl",
    name: "Perl",
    description:
      "Became the 'Swiss Army knife' of programming, particularly popular for system administration and web development in the early internet era.",
    year: 1987,
    url: "https://en.wikipedia.org/wiki/Perl",
    tags: [
      "1980s",
      "programming-language",
      "scripting-language",
      "text-processing",
      "general-purpose-language",
    ],
    dependsOn: ["c", "shell", "awk", "unix"],
  },
  {
    id: "self",
    name: "Self",
    description:
      "Pioneered prototype-based object-oriented programming and just-in-time compilation, influencing languages like JavaScript.",
    year: 1987,
    url: "https://en.wikipedia.org/wiki/Self_(programming_language)",
    tags: ["1980s", "programming-language", "general-purpose-language"],
    dependsOn: ["smalltalk"],
  },
  {
    id: "clos",
    name: "CLOS",
    description:
      "Object system for Common Lisp, pioneering multiple dispatch and method combinations.",
    year: 1988,
    url: "https://en.wikipedia.org/wiki/Common_Lisp_Object_System",
    tags: ["1980s", "programming-language", "general-purpose-language"],
    dependsOn: ["smalltalk", "lisp"],
  },
  {
    id: "tcl",
    name: "Tcl",
    description:
      "Designed as an embeddable scripting language, widely used for rapid prototyping, scripted applications, GUIs, and testing.",
    year: 1988,
    url: "https://en.wikipedia.org/wiki/Tcl",
    tags: ["1980s", "programming-language", "scripting-language"],
    dependsOn: ["awk", "lisp"],
  },
  {
    id: "haskell",
    name: "Haskell",
    description:
      "Standardized purely functional programming, influencing language design and promoting functional concepts in mainstream programming.",
    year: 1990,
    url: "https://en.wikipedia.org/wiki/Haskell_(programming_language)",
    tags: ["1980s", "programming-language", "general-purpose-language"],
    dependsOn: ["miranda", "ml"],
  },
  {
    id: "python",
    name: "Python",
    description:
      "Emphasizing code readability and simplicity, Python became one of the most popular languages, particularly in scientific computing and data science.",
    year: 1991,
    url: "https://en.wikipedia.org/wiki/Python_(programming_language)",
    tags: [
      "1990s",
      "programming-language",
      "general-purpose-language",
      "scripting-language",
    ],
    dependsOn: ["abc", "c", "modula", "lisp", "icon"],
  },
  {
    id: "visual-basic",
    name: "Visual Basic",
    description:
      "Simplified Windows application development, playing a crucial role in the rapid application development era of the 1990s.",
    year: 1991,
    url: "https://en.wikipedia.org/wiki/Visual_Basic",
    tags: ["1990s", "programming-language", "business"],
    dependsOn: ["basic"],
  },
  {
    id: "dylan",
    name: "Dylan",
    description:
      "Designed to combine the simplicity of Scheme with features of object-oriented languages, aiming for both dynamic and efficient compilation.",
    year: 1992,
    url: "https://en.wikipedia.org/wiki/Dylan_(programming_language)",
    tags: ["1990s", "programming-language", "general-purpose-language"],
    dependsOn: ["scheme", "clos"],
  },
  {
    id: "applescript",
    name: "AppleScript",
    description:
      "Scripting language designed by Apple to enable easy control of scriptable applications, playing a key role in Mac automation.",
    year: 1993,
    url: "https://en.wikipedia.org/wiki/AppleScript",
    tags: ["1990s", "programming-language", "scripting-language"],
    dependsOn: ["macintosh", "hypertalk"],
  },
  {
    id: "lua",
    name: "Lua",
    description:
      "Lightweight scripting language designed for embedding, gaining wide adoption in game development and application extension.",
    year: 1993,
    url: "https://en.wikipedia.org/wiki/Lua_(programming_language)",
    tags: [
      "1990s",
      "programming-language",
      "scripting-language",
      "general-purpose-language",
    ],
    dependsOn: ["self", "scheme", "modula"],
  },
  {
    id: "r",
    name: "R",
    description:
      "Open-source implementation of S, becoming the de facto standard for statistical computing and data analysis in academia and industry.",
    year: 1993,
    url: "https://en.wikipedia.org/wiki/R_(programming_language)",
    tags: ["1990s", "programming-language", "scientific"],
    dependsOn: ["s", "scheme"],
  },
  {
    id: "mercury",
    name: "Mercury",
    description:
      "Functional and logic programming language built on the foundations of Prolog but with static typing and higher-order programming.",
    year: 1995,
    url: "https://en.wikipedia.org/wiki/Mercury_(programming_language)",
    tags: [
      "1990s",
      "programming-language",
      "general-purpose-language",
      "artificial-intelligence",
    ],
    dependsOn: ["prolog", "haskell"],
  },
  {
    id: "ruby",
    name: "Ruby",
    description:
      "Combined object-oriented programming with functional features, gaining popularity through the Ruby on Rails web framework.",
    year: 1995,
    url: "https://en.wikipedia.org/wiki/Ruby_(programming_language)",
    tags: [
      "1990s",
      "programming-language",
      "general-purpose-language",
      "scripting-language",
    ],
    dependsOn: ["perl", "smalltalk", "lisp"],
  },
  {
    id: "java",
    name: "Java",
    description:
      "Popularized 'write once, run anywhere' philosophy, becoming dominant in enterprise software and forming the basis of the Android mobile operating system.",
    year: 1995,
    url: "https://en.wikipedia.org/wiki/Java_(programming_language)",
    tags: [
      "1990s",
      "programming-language",
      "general-purpose-language",
      "business",
    ],
    dependsOn: ["c++", "smalltalk", "objective-c", "unicode"],
  },
  {
    id: "javascript",
    name: "JavaScript",
    description:
      "Originally designed for client-side web scripting, it became the universal language of the web and later expanded to server-side development.",
    year: 1995,
    url: "https://en.wikipedia.org/wiki/JavaScript",
    tags: ["1990s", "programming-language", "web", "general-purpose-language"],
    dependsOn: ["www", "scheme", "self", "hypertalk", "unicode"],
  },
  {
    id: "php",
    name: "PHP",
    description:
      "Designed for web development, it became one of the most widely used server-side scripting languages, powering a large portion of the early dynamic web.",
    year: 1995,
    url: "https://en.wikipedia.org/wiki/PHP",
    tags: ["1990s", "programming-language", "web", "general-purpose-language"],
    dependsOn: ["www", "perl", "c"],
  },
  {
    id: "ocaml",
    name: "OCaml",
    description:
      "Functional programming language from the ML family, known for its speed and expressiveness, influential in both academia and industry.",
    year: 1996,
    url: "https://en.wikipedia.org/wiki/OCaml",
    tags: ["1990s", "programming-language", "general-purpose-language"],
    dependsOn: ["ml"],
  },
  {
    id: "actionscript",
    name: "ActionScript",
    description:
      "Scripting language for the Adobe Flash platform, crucial in the development of interactive web content and online games in the 2000s.",
    year: 2000,
    url: "https://en.wikipedia.org/wiki/ActionScript",
    tags: ["1990s", "programming-language", "web"],
    dependsOn: ["www", "javascript", "hypertalk"],
  },
  {
    id: "c-sharp",
    name: "C#",
    description:
      "Developed by Microsoft as part of the .NET framework, evolving into a versatile language for Windows and cross-platform development.",
    year: 2000,
    url: "https://en.wikipedia.org/wiki/C_Sharp_(programming_language)",
    tags: [
      "2000s",
      "programming-language",
      "general-purpose-language",
      "business",
    ],
    dependsOn: ["c++", "java"],
  },
  {
    id: "vbnet",
    name: "Visual Basic .NET",
    description:
      "Object-oriented version of Visual Basic, part of the .NET Framework, facilitating the transition of VB6 developers to the .NET platform.",
    year: 2001,
    url: "https://en.wikipedia.org/wiki/Visual_Basic_.NET",
    tags: [
      "2000s",
      "programming-language",
      "general-purpose-language",
      "business",
    ],
    dependsOn: ["visual-basic", "c-sharp"],
  },
  {
    id: "scala",
    name: "Scala",
    description:
      "Combined object-oriented and functional programming, gaining popularity in big data processing and distributed computing.",
    year: 2003,
    url: "https://en.wikipedia.org/wiki/Scala_(programming_language)",
    tags: [
      "2000s",
      "programming-language",
      "general-purpose-language",
      "concurrent-language",
    ],
    dependsOn: ["java", "haskell"],
  },
  {
    id: "f-sharp",
    name: "F#",
    description:
      "Functional-first language for the .NET ecosystem, bringing functional programming concepts to the .NET platform.",
    year: 2005,
    url: "https://en.wikipedia.org/wiki/F_Sharp_(programming_language)",
    tags: [
      "2000s",
      "programming-language",
      "general-purpose-language",
      "scientific",
    ],
    dependsOn: ["ocaml", "c-sharp"],
  },
  {
    id: "scratch",
    name: "Scratch",
    description:
      "Visual programming language aimed at making programming accessible to children and beginners.",
    year: 2007,
    url: "https://en.wikipedia.org/wiki/Scratch_(programming_language)",
    tags: ["2000s", "programming-language", "education"],
    dependsOn: ["logo"],
  },
  {
    id: "go",
    name: "Go",
    description:
      "Designed for simplicity and efficiency in concurrent programming, gaining rapid adoption in cloud computing and microservices architectures.",
    year: 2009,
    url: "https://en.wikipedia.org/wiki/Go_(programming_language)",
    tags: [
      "2000s",
      "programming-language",
      "systems-language",
      "concurrent-language",
    ],
    dependsOn: ["c", "oberon", "modula"],
  },
  {
    id: "rust",
    name: "Rust",
    description:
      "Focused on memory safety without sacrificing performance, gaining traction in systems programming and as a safer alternative to C and C++.",
    year: 2010,
    url: "https://en.wikipedia.org/wiki/Rust_(programming_language)",
    tags: [
      "2010s",
      "programming-language",
      "systems-language",
      "concurrent-language",
    ],
    dependsOn: ["c++", "haskell", "ocaml"],
  },
  {
    id: "dart",
    name: "Dart",
    description:
      "Developed by Google for building mobile, desktop, and web applications, notable for its use in the Flutter framework.",
    year: 2011,
    url: "https://en.wikipedia.org/wiki/Dart_(programming_language)",
    tags: ["2010s", "programming-language", "general-purpose-language", "web"],
    dependsOn: ["www", "java", "javascript"],
  },
  {
    id: "elixir",
    name: "Elixir",
    description:
      "Functional, concurrent language built on top of the Erlang VM, designed for building scalable and maintainable applications.",
    year: 2011,
    url: "https://en.wikipedia.org/wiki/Elixir_(programming_language)",
    tags: [
      "2010s",
      "programming-language",
      "concurrent-language",
      "general-purpose-language",
    ],
    dependsOn: ["erlang", "ruby"],
  },
  {
    id: "elm",
    name: "Elm",
    description:
      "Functional language for declarative web UIs, influencing state management in other front-end frameworks.",
    year: 2012,
    url: "https://en.wikipedia.org/wiki/Elm_(programming_language)",
    tags: ["2010s", "programming-language", "web"],
    dependsOn: ["www", "haskell", "ml"],
  },
  {
    id: "julia",
    name: "Julia",
    description:
      "Designed for high-performance numerical and scientific computing while being easy to use, aiming to bridge the gap between scripting and compiled languages.",
    year: 2012,
    url: "https://en.wikipedia.org/wiki/Julia_(programming_language)",
    tags: [
      "2010s",
      "programming-language",
      "scientific",
      "scripting-language",
      "general-purpose-language",
    ],
    dependsOn: ["matlab", "r", "python", "lisp"],
  },
  {
    id: "typescript",
    name: "TypeScript",
    description:
      "Superset of JavaScript adding optional static typing, enhancing tooling and scalability for large JavaScript projects.",
    year: 2012,
    url: "https://en.wikipedia.org/wiki/TypeScript",
    tags: ["2010s", "programming-language", "web", "general-purpose-language"],
    dependsOn: ["javascript", "c-sharp"],
  },
  {
    id: "swift",
    name: "Swift",
    description:
      "Developed by Apple as a replacement for Objective-C, quickly becoming the primary language for iOS and macOS development.",
    year: 2014,
    url: "https://en.wikipedia.org/wiki/Swift_(programming_language)",
    tags: ["2010s", "programming-language", "general-purpose-language"],
    dependsOn: ["objective-c", "rust", "haskell", "c-sharp"],
  },
];

const allNodes = [...generalNodes, ...progLangNodes];
